### ISSUE TITLE
bug: Type 'T' does not satisfy the constraint 'object'

### ISSUE THREAD

**Issue by kieran-s** [sapphiredev/shapeshift#197] opened 2022-09-18 11:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

https://stackoverflow.com/questions/73761953/sapphire-shapeshift-discordjs-type-t-does-not-satisfy-the-constraint-objec

Using DiscordJS and typescript, when I try to build using TSC, I get errors in sapphire/shapeshift

```
node_modules/@sapphire/shapeshift/dist/index.d.ts:590:44 - error TS2344: Type 'T' does not satisfy the constraint 'object'.

590 declare type SchemaOf<T> = ObjectValidator<T>;
                                               ~

  node_modules/@sapphire/shapeshift/dist/index.d.ts:590:23
    590 declare type SchemaOf<T> = ObjectValidator<T>;
                              ~
    This type parameter might need an `extends object` constraint.

node_modules/@sapphire/shapeshift/dist/index.d.ts:641:65 - error TS2344: Type 'T' does not satisfy the constraint 'object'.

641     object<T>(shape: MappedObjectValidator<T>): ObjectValidator<T, UndefinedToOptional<T>>;
                                                                    ~

  node_modules/@sapphire/shapeshift/dist/index.d.ts:641:12
    641     object<T>(shape: MappedObjectValidator<T>): ObjectValidator<T, UndefinedToOptional<T>>;
                   ~
    This type parameter might need an `extends object` constraint.


Found 2 errors in the same file, starting at: node_modules/@sapphire/shapeshift/dist/index.d.ts:590
```

### Steps To Reproduce

1. Setup a project using DiscordJS14 and typescript
2. Build using TSC

### Expected behavior

Builds properly

**Comment by imranbarbhuiya** [comment] 2022-09-18 12:38
Duplicate of #193

check the reply in that issue

**Comment by favna** [comment] 2022-09-18 12:42
Closing as per the above comment

**Closed by favna** 2022-09-18 12:42 UTC

**Comment by kieran-s** [comment] 2022-09-18 12:49
Ah thanks, missed that issue!
Using yarn resolutions per that reply fixed it.
